"""Karten zum Cytochrom-P450-System (Lückentext). Jede Lücke {{cN::…}} wird zu einer eigenen Karte.

Format: SECTIONS = [(Unterdeck, [(Text, Extra), ...]), ...]
"""

SECTIONS = [
    ("01 Grundlagen und Aufbau", [
        ("Cytochrom-P450-Enzyme sind {{c1::Hämproteine}}, deren Eisen über einen {{c2::Cystein-Thiolat}}-Liganden gebunden ist.",
         "Häm-Thiolat-Proteine. Das Fe wechselt im Reaktionszyklus zwischen Fe³⁺ und Fe²⁺."),
        ("Der Name „P450“ kommt vom Absorptionsmaximum bei {{c1::450 nm}}, das das reduzierte Enzym im Komplex mit {{c2::Kohlenmonoxid (CO)}} zeigt.",
         "P = Pigment."),
        ("CYP450-Enzyme der Arzneistoff-Biotransformation liegen v. a. in der Membran des {{c1::glatten endoplasmatischen Retikulums}} der {{c2::Hepatozyten}}.",
         "Labormethodisch: „mikrosomale“ Enzyme. Die CYPs der Steroidhormonsynthese liegen dagegen teils in den Mitochondrien (z. B. CYP11A1, CYP11B1, CYP11B2)."),
        ("Außerhalb der Leber kommt v. a. {{c1::CYP3A4}} in relevanter Menge in den {{c2::Enterozyten des Dünndarms}} vor und trägt zum First-Pass-Effekt bei.",
         "Weitere Orte mit CYP-Aktivität: Lunge, Niere, Haut, Gehirn, Nebenniere, Plazenta."),
        ("Innerhalb des Leberläppchens ist die CYP-Aktivität in der {{c1::perivenösen Zone 3 (um die Zentralvene)}} am höchsten.",
         "Deshalb verursachen Gifte, die über CYP aktiviert werden (z. B. Paracetamol → NAPQI, Tetrachlorkohlenstoff), typischerweise zentrolobuläre Nekrosen."),
        ("CYP450-Enzyme sind {{c1::Monooxygenasen}} (mischfunktionelle Oxidasen): Ein O-Atom aus O₂ wird in das {{c2::Substrat}} eingebaut, das andere zu {{c3::Wasser}} reduziert.",
         "Summengleichung: RH + O₂ + NADPH + H⁺ → ROH + H₂O + NADP⁺"),
        ("Die Elektronen für die CYP-Reaktion stammen von {{c1::NADPH}} und werden über die {{c2::NADPH-Cytochrom-P450-Reduktase}} übertragen.",
         "Die Reduktase enthält die Flavine FAD und FMN. Teilweise liefert auch Cytochrom b5 Elektronen."),
        ("Nomenklatur am Beispiel CYP3A4: „3“ = {{c1::Familie}}, „A“ = {{c2::Subfamilie}}, „4“ = {{c3::einzelnes Isoenzym}}.",
         "Familie: ≥ 40 % Sequenzidentität, Subfamilie: ≥ 55 %."),
        ("Das quantitativ wichtigste Isoenzym für Arzneistoffe ist {{c1::CYP3A4}}; es ist am Abbau von ca. {{c2::30–50 %}} aller Arzneistoffe beteiligt.",
         "Danach folgen etwa CYP2D6, CYP2C9, CYP2C19 und CYP1A2. Diese fünf Isoenzyme erklären den Großteil aller CYP-Interaktionen."),
    ]),
    ("02 Biotransformation Phase I und II", [
        ("CYP450-Reaktionen gehören zur {{c1::Phase I}} der Biotransformation (Funktionalisierung).",
         "Ziel: Einführen oder Freilegen einer funktionellen Gruppe (–OH, –NH₂, –SH, –COOH) als Angriffspunkt für Phase II."),
        ("Typische CYP-katalysierte Phase-I-Reaktionen: {{c1::Hydroxylierung}}, {{c2::N-/O-Dealkylierung}}, {{c3::Epoxidierung}}, {{c4::S-Oxidation}}.",
         "Weitere: oxidative Desaminierung, Dehalogenierung. Andere Phase-I-Reaktionen (Reduktion, Hydrolyse) laufen meist über andere Enzyme (z. B. Esterasen)."),
        ("Phase-II-Reaktionen sind {{c1::Konjugationen}} mit körpereigenen Molekülen, z. B. {{c2::Glucuronsäure}}, Sulfat, Glutathion, Acetyl- oder Methylgruppen.",
         "Häufigste Phase-II-Reaktion: Glucuronidierung durch UDP-Glucuronosyltransferasen (UGT). Phase II ist meist kein CYP-Schritt."),
        ("Ziel der Biotransformation ist es, lipophile Stoffe {{c1::hydrophiler}} und damit {{c2::renal oder biliär ausscheidbar}} zu machen.",
         "Lipophile Stoffe würden im Tubulus rückresorbiert."),
        ("Phase-I-Produkte sind meist inaktiv, können aber auch {{c1::aktive Metabolite}} (Prodrug-Aktivierung) oder {{c2::toxische/kanzerogene Metabolite}} (Giftung) sein.",
         "Beispiele Aktivierung: Clopidogrel, Codein, Tamoxifen, Losartan, Cyclophosphamid.<br>Beispiele Giftung: Paracetamol → NAPQI, Benzo[a]pyren → Diolepoxid."),
        ("Bei Leberzirrhose und im Alter ist die {{c1::Phase I (CYP)}} stärker eingeschränkt als die {{c2::Glucuronidierung}}.",
         "Praktische Folge siehe Benzodiazepine: Lorazepam, Oxazepam, Temazepam werden nur glucuronidiert."),
        ("Bei Leberinsuffizienz sind unter den Benzodiazepinen {{c1::Lorazepam, Oxazepam, Temazepam}} zu bevorzugen, da sie {{c2::direkt glucuronidiert}} werden.",
         "Merkhilfe „LOT“. Diazepam dagegen: CYP-Abbau (2C19, 3A4), lange wirksame aktive Metabolite (Nordazepam) → Kumulation."),
        ("Der hepatische {{c1::First-Pass-Effekt}} ist besonders hoch bei CYP3A4-Substraten wie {{c2::Simvastatin}}; deren orale Bioverfügbarkeit liegt deshalb deutlich unter 10 %.",
         "Daher wirken intestinale CYP3A4-Hemmer (Grapefruitsaft) besonders stark auf oral gegebene Substrate mit hohem First Pass."),
    ]),
    ("03 Wichtige Isoenzyme und Substrate", [
        ("CYP3A4-Substrate (Immunsuppressiva): {{c1::Ciclosporin}}, {{c2::Tacrolimus}}, {{c3::Sirolimus/Everolimus}}.",
         "Enge therapeutische Breite → Spiegelkontrolle (TDM) bei jeder Änderung der Begleitmedikation."),
        ("CYP3A4-Substrate unter den Statinen: {{c1::Simvastatin}}, {{c2::Lovastatin}}, {{c3::Atorvastatin}}.",
         "Nicht (relevant) über CYP3A4: Pravastatin, Rosuvastatin (beide kaum CYP), Fluvastatin (CYP2C9)."),
        ("Bei notwendiger Komedikation mit starken CYP3A4-Hemmern eignen sich als Statine eher {{c1::Pravastatin}} oder {{c2::Rosuvastatin}}.",
         "Sie werden kaum über CYP abgebaut. Achtung: Rosuvastatin hat Transporter-Interaktionen (z. B. Ciclosporin über OATP1B1)."),
        ("Weitere wichtige CYP3A4-Substrate: {{c1::Midazolam}}, {{c2::Dihydropyridin-Calciumantagonisten (z. B. Amlodipin, Felodipin)}}, {{c3::HIV-Proteaseinhibitoren}}.",
         "Außerdem: Fentanyl, Oxycodon, Sildenafil, Ticagrelor, Apixaban/Rivaroxaban (teilweise), Glukokortikoide, Östrogene/Gestagene, Kolchizin, Ergotamin, viele Tyrosinkinasehemmer."),
        ("Orale hormonelle Kontrazeptiva (Ethinylestradiol, Gestagene) werden über {{c1::CYP3A4}} abgebaut.",
         "Deshalb verlieren sie unter CYP3A4-Induktoren (Rifampicin, Carbamazepin, Johanniskraut) an Wirkung → zusätzliche Verhütung nötig."),
        ("CYP2D6-Substrate: Opioide {{c1::Codein}} und {{c2::Tramadol}} (Aktivierung), β-Blocker {{c3::Metoprolol}}.",
         "Weitere: trizyklische Antidepressiva (Amitriptylin, Nortriptylin), Haloperidol, Risperidon, Dextromethorphan, Tamoxifen (Aktivierung), Flecainid, Propafenon."),
        ("CYP2C9-Substrate: {{c1::Warfarin (S-Enantiomer)}}/Phenprocoumon, {{c2::Phenytoin}}, {{c3::Sulfonylharnstoffe}}, {{c4::NSAR (z. B. Ibuprofen, Diclofenac, Celecoxib)}}.",
         "Außerdem Losartan (Aktivierung zum aktiven Metaboliten E-3174) und Fluvastatin."),
        ("CYP2C19-Substrate: {{c1::Clopidogrel}} (Aktivierung), {{c2::Protonenpumpenhemmer (v. a. Omeprazol)}}, Diazepam, {{c3::Citalopram/Escitalopram}}.",
         "Auch Voriconazol wird überwiegend via CYP2C19 abgebaut."),
        ("CYP1A2-Substrate: {{c1::Theophyllin}}, {{c2::Clozapin}}, {{c3::Olanzapin}}, {{c4::Koffein}}.",
         "Weitere: Duloxetin, Tizanidin, Melatonin, Ropinirol."),
        ("CYP2E1 baut {{c1::Ethanol}} (im MEOS) ab und aktiviert {{c2::Paracetamol}} zum toxischen {{c3::NAPQI}}.",
         "MEOS = mikrosomales ethanoloxidierendes System. CYP2E1 aktiviert außerdem Inhalationsanästhetika (Halothan) und Lösungsmittel; induziert wird es durch chronischen Alkoholkonsum und Isoniazid."),
        ("CYP2B6 ist u. a. wichtig für {{c1::Efavirenz}}, {{c2::Bupropion}} und die Aktivierung von {{c3::Cyclophosphamid}}.",
         "Cyclophosphamid ist ein Prodrug: Hydroxylierung (CYP2B6, auch 2C19, 3A4) → 4-Hydroxy-Cyclophosphamid → Phosphoramid-Lost (wirksam) + Acrolein (Urotoxizität → Mesna)."),
        ("CYP1A1 aktiviert {{c1::polyzyklische aromatische Kohlenwasserstoffe (z. B. Benzo[a]pyren)}} aus Tabakrauch zu {{c2::kanzerogenen Epoxiden}}.",
         "Induktion über den Arylhydrocarbon-Rezeptor (AhR)."),
    ]),
    ("04 Enzyminduktion", [
        ("Enzyminduktoren steigern die {{c1::Transkription (Neusynthese)}} von CYP-Enzymen über nukleäre Rezeptoren wie {{c2::PXR}}, {{c3::CAR}} und den AhR.",
         "PXR = Pregnan-X-Rezeptor (v. a. CYP3A4, P-Glykoprotein), CAR = konstitutiver Androstan-Rezeptor (u. a. CYP2B6), AhR = Arylhydrocarbon-Rezeptor (CYP1A1/1A2)."),
        ("Eine Enzyminduktion setzt {{c1::langsam (über ca. 1–2 Wochen)}} ein und klingt nach Absetzen des Induktors auch {{c2::langsam (über Wochen)}} ab.",
         "Grund: Neusynthese bzw. Abbau von Enzymprotein. Hemmung dagegen wirkt innerhalb von Stunden bis Tagen."),
        ("Der stärkste klinisch relevante CYP-Induktor ist das Tuberkulostatikum {{c1::Rifampicin}}.",
         "Induziert CYP3A4, 2C9, 2C19, 1A2 und P-Glykoprotein. Rifabutin induziert schwächer."),
        ("Antiepileptika mit starker Enzyminduktion: {{c1::Carbamazepin}}, {{c2::Phenytoin}}, {{c3::Phenobarbital/Primidon}}.",
         "Auch Oxcarbazepin (schwächer, v. a. CYP3A4 → Pille!) und Topiramat (dosisabhängig). Valproat ist dagegen ein Enzymhemmer."),
        ("Das pflanzliche Antidepressivum {{c1::Johanniskraut}} induziert über seinen Inhaltsstoff {{c2::Hyperforin}} CYP3A4 und P-Glykoprotein.",
         "Typische Folgen: Pillenversagen, Transplantatabstoßung (Ciclosporin↓), Wirkverlust von HIV-Medikamenten und Antikoagulanzien. Wird oft nicht als „Medikament“ angegeben → gezielt fragen!"),
        ("{{c1::Tabakrauchen}} induziert {{c2::CYP1A2}} über polyzyklische Kohlenwasserstoffe (nicht über Nikotin).",
         "Raucher brauchen deshalb höhere Dosen von Clozapin, Olanzapin, Theophyllin. Nikotinersatz induziert nicht."),
        ("Hört ein Patient unter Clozapin auf zu rauchen, {{c1::steigt der Clozapin-Spiegel deutlich an}} (Gefahr von {{c2::Krampfanfällen, Sedierung, Hypersalivation}}).",
         "Wegfall der CYP1A2-Induktion. Spiegelkontrolle und ggf. Dosisreduktion um ca. 30–50 %. Auch bei Klinikaufnahme mit Rauchverbot beachten!"),
        ("{{c1::Chronischer}} Alkoholkonsum induziert CYP2E1, {{c2::akuter}} Alkoholkonsum hemmt den Abbau anderer CYP2E1-Substrate eher kompetitiv.",
         "Klinik: Chronische Alkoholkonsumenten brauchen nüchtern oft höhere Dosen von Sedativa/Narkotika (Toleranz durch Induktion), sind aber durch Paracetamol stärker gefährdet. Akut alkoholisiert wirken Sedativa dagegen verstärkt."),
        ("{{c1::Carbamazepin}} induziert seinen eigenen Abbau ({{c2::Autoinduktion}}); die Halbwertszeit sinkt in den ersten Wochen deutlich.",
         "Deshalb einschleichend dosieren und nach 2–4 Wochen Spiegel kontrollieren und ggf. Dosis erhöhen."),
        ("Enzyminduktoren machen die {{c1::orale hormonelle Kontrazeption}} unsicher; empfohlen werden z. B. {{c2::Kupferspirale oder Depot-Medroxyprogesteronacetat}}.",
         "Auch die Notfallkontrazeption (Levonorgestrel) muss unter Induktoren angepasst werden (doppelte Dosis) oder es wird eine Kupferspirale empfohlen. Die Induktion hält bis ca. 4 Wochen nach Absetzen an."),
        ("Unter Rifampicin sinkt die INR bei Vitamin-K-Antagonisten; nach {{c1::Absetzen von Rifampicin}} droht dagegen eine {{c2::Blutung durch INR-Anstieg}}.",
         "Klassische Interaktionsfalle: Die Dosis des Antikoagulans wurde unter Induktion hochtitriert und wird nach Ende der Tbc-Therapie nicht reduziert."),
        ("Unter Enzyminduktoren drohen bei Transplantierten {{c1::subtherapeutische Ciclosporin-/Tacrolimus-Spiegel}} mit {{c2::Abstoßungsreaktion}}.",
         "Rifampicin, Johanniskraut, Carbamazepin, Phenytoin meiden oder sehr engmaschig Spiegel messen."),
        ("Viele Induktoren von CYP3A4 induzieren gleichzeitig den Efflux-Transporter {{c1::P-Glykoprotein (MDR1/ABCB1)}}.",
         "Deshalb sinken z. B. auch Digoxin- und Dabigatran-Spiegel unter Rifampicin oder Johanniskraut, obwohl beide kaum über CYP abgebaut werden."),
    ]),
    ("05 Enzymhemmung", [
        ("CYP-Hemmung wirkt {{c1::schnell (innerhalb von Stunden bis wenigen Tagen)}}, da kein Enzym neu gebildet werden muss.",
         "Mechanismen: kompetitiv (reversibel) oder mechanismusbasiert/irreversibel (z. B. Clarithromycin, Grapefruit-Furanocumarine): dann erst Erholung durch Enzymneusynthese."),
        ("Makrolide mit starker CYP3A4-Hemmung: {{c1::Clarithromycin}} und {{c2::Erythromycin}}; kaum hemmend ist dagegen {{c3::Azithromycin}}.",
         "Azithromycin ist bei Interaktionsrisiko das Makrolid der Wahl (QT-Verlängerung trotzdem beachten)."),
        ("Azol-Antimykotika mit starker CYP3A4-Hemmung: {{c1::Ketoconazol}}, {{c2::Itraconazol}}, {{c3::Posaconazol}}, {{c4::Voriconazol}}.",
         "Fluconazol hemmt v. a. CYP2C9 und CYP2C19 stark und CYP3A4 mäßig (dosisabhängig)."),
        ("{{c1::Fluconazol}} hemmt besonders stark {{c2::CYP2C9}} und erhöht so z. B. die Wirkung von Phenprocoumon/Warfarin und Phenytoin.",
         "Auch bei Einmalgabe (Vaginalmykose) INR kontrollieren."),
        ("Der Wirkmechanismus der Azol-Antimykotika ist die Hemmung des pilzeigenen CYP-Enzyms {{c1::Lanosterol-14α-Demethylase (CYP51)}} und damit der {{c2::Ergosterol}}-Synthese.",
         "Die Hemmung menschlicher CYPs ist eine „Nebenwirkung“ derselben Hämbindung (Azol-Stickstoff bindet an das Häm-Eisen)."),
        ("Die HIV-Medikamente {{c1::Ritonavir}} und {{c2::Cobicistat}} sind starke CYP3A4-Hemmer und werden gezielt als {{c3::„Booster“}} eingesetzt.",
         "Niedrig dosiert erhöhen sie die Spiegel anderer Proteaseinhibitoren (z. B. Darunavir). Auch in Paxlovid® (Nirmatrelvir + Ritonavir) → zahlreiche Kontraindikationen (z. B. Simvastatin, Midazolam oral, Amiodaron)."),
        ("{{c1::Grapefruitsaft}} hemmt v. a. das {{c2::intestinale}} CYP3A4 über {{c3::Furanocumarine (z. B. Bergamottin)}}.",
         "Irreversible Hemmung, Effekt hält ca. 24–72 h an (ein Glas reicht). Betrifft v. a. oral gegebene Substrate mit hohem First Pass: Simvastatin, Felodipin, Ciclosporin, Midazolam. Auch Pomelo und Bitterorange, nicht normaler Orangensaft."),
        ("Die Calciumantagonisten {{c1::Verapamil}} und {{c2::Diltiazem}} hemmen CYP3A4 (und P-Glykoprotein); Dihydropyridine wie Amlodipin kaum.",
         "Klinisch z. B.: Simvastatin max. 20 mg mit Amlodipin, mit Verapamil/Diltiazem Simvastatin möglichst vermeiden oder niedrig dosieren."),
        ("{{c1::Amiodaron}} hemmt mehrere CYPs (u. a. {{c2::CYP2C9}}, 3A4, 2D6) sowie P-Glykoprotein; wegen der extrem langen Halbwertszeit hält die Hemmung {{c3::monatelang}} an.",
         "Wichtig: Phenprocoumon/Warfarin-Dosis reduzieren (INR↑), Digoxin-Dosis halbieren (P-gp), Simvastatin max. 20 mg."),
        ("{{c1::Ciprofloxacin}} und das SSRI {{c2::Fluvoxamin}} sind starke Hemmer von {{c3::CYP1A2}}.",
         "Folge: Theophyllin-Intoxikation (Krampfanfälle, Tachyarrhythmien), Clozapin↑, Tizanidin↑ (Hypotonie; Kombination mit Fluvoxamin/Cipro kontraindiziert)."),
        ("Die SSRI {{c1::Fluoxetin}} und {{c2::Paroxetin}} sowie {{c3::Bupropion}} sind starke {{c4::CYP2D6}}-Hemmer.",
         "Folgen: weniger Codein-/Tramadol-Wirkung, weniger Tamoxifen-Wirkung, mehr Metoprolol-/TCA-Spiegel. Bei Tamoxifen besser Venlafaxin oder (Es-)Citalopram."),
        ("{{c1::Omeprazol}} und {{c2::Esomeprazol}} hemmen CYP2C19 und können so die Aktivierung von {{c3::Clopidogrel}} vermindern.",
         "Bei Clopidogrel daher eher Pantoprazol (geringere CYP2C19-Hemmung) einsetzen."),
        ("Die H₂-Blocker-Substanz {{c1::Cimetidin}} ist ein unspezifischer CYP-Hemmer; bei {{c2::Famotidin}} spielt das kaum eine Rolle.",
         "Klassisches Prüfungsbeispiel, klinisch heute selten."),
        ("Die Antiinfektiva {{c1::Metronidazol}} und {{c2::Cotrimoxazol}} hemmen CYP2C9 → Wirkungsverstärkung von {{c3::Vitamin-K-Antagonisten}}.",
         "Cotrimoxazol verstärkt über CYP2C9 auch Sulfonylharnstoffe (Hypoglykämie) und Phenytoin."),
        ("{{c1::Valproat}} ist (anders als Carbamazepin und Phenytoin) ein {{c2::Enzymhemmer}} und erhöht z. B. die Spiegel von {{c3::Lamotrigin}}.",
         "Hemmung v. a. der Glucuronidierung (UGT) und von CYP2C9. Lamotrigin unter Valproat langsamer aufdosieren (Gefahr: Stevens-Johnson-Syndrom)."),
    ]),
    ("06 Klinisch wichtige Interaktionen", [
        ("Simvastatin + Clarithromycin/Itraconazol: Gefahr einer {{c1::Rhabdomyolyse}}.",
         "Mechanismus: CYP3A4-Hemmung → Statinspiegel ↑↑. Simvastatin während der Antibiose pausieren oder auf Pravastatin/Rosuvastatin wechseln."),
        ("Ciclosporin/Tacrolimus + Makrolid/Azol: Spiegelanstieg mit Gefahr von {{c1::Nephrotoxizität}} und Neurotoxizität.",
         "Weitere Calcineurininhibitor-Toxizität: Hypertonie, Hyperkaliämie, Hypomagnesiämie, Tremor. Immer TDM."),
        ("Midazolam + starker CYP3A4-Hemmer: {{c1::verlängerte Sedierung und Atemdepression}}.",
         "Orales Midazolam mit Ritonavir/Ketoconazol ist kontraindiziert (hoher First Pass fällt weg)."),
        ("Kombination eines starken CYP3A4-Hemmers mit einem QT-verlängernden CYP3A4-Substrat: Gefahr von {{c1::Torsade-de-pointes-Tachykardien}}.",
         "Historisch: Terfenadin oder Cisaprid + Ketoconazol/Erythromycin → Marktrücknahmen. Heute z. B. Clarithromycin + Domperidon oder + Quetiapin. Makrolide verlängern zusätzlich selbst die QT-Zeit."),
        ("Kolchizin + Clarithromycin: lebensbedrohliche {{c1::Kolchizin-Intoxikation}} (Hemmung von CYP3A4 und P-Glykoprotein).",
         "Symptome: Durchfall, Erbrechen, Myopathie, Panzytopenie, Multiorganversagen."),
        ("Ergotamin + starker CYP3A4-Hemmer (Makrolid, Ritonavir): Gefahr des {{c1::Ergotismus}} mit Vasospasmen und Ischämien.",
         "Kontraindizierte Kombination."),
        ("Phenprocoumon/Warfarin + Amiodaron, Fluconazol, Metronidazol oder Cotrimoxazol: {{c1::INR-Anstieg mit Blutungsgefahr}} (CYP2C9-Hemmung).",
         "Kurzfristig INR kontrollieren und Dosis anpassen. Antibiotika verstärken VKA zusätzlich über die Darmflora (Vitamin-K2-Mangel)."),
        ("Theophyllin + Ciprofloxacin: Gefahr einer {{c1::Theophyllin-Intoxikation}} durch CYP1A2-Hemmung.",
         "Symptome: Übelkeit, Unruhe, Tachykardie/Arrhythmien, Krampfanfälle. Theophyllin hat eine enge therapeutische Breite."),
        ("Clopidogrel ist ein {{c1::Prodrug}}, das über {{c2::CYP2C19}} in seinen aktiven Thiol-Metaboliten umgewandelt wird.",
         "Prasugrel wird weniger abhängig von CYP2C19 aktiviert; Ticagrelor ist direkt wirksam (aber CYP3A4-Substrat)."),
        ("Phenytoin hat eine {{c1::nichtlineare (sättigbare) Kinetik}}: Kleine Dosiserhöhungen können zu {{c2::unverhältnismäßig hohen Spiegeln}} führen.",
         "Grund: Sättigung von CYP2C9/2C19 im therapeutischen Bereich (Michaelis-Menten-Kinetik). Toxizitätszeichen: Nystagmus, Ataxie, Dysarthrie."),
        ("{{c1::Digoxin}} und {{c2::Dabigatran}} werden kaum über CYP abgebaut; ihre Interaktionen laufen über {{c3::P-Glykoprotein}}.",
         "P-gp-Hemmer (Verapamil, Amiodaron, Clarithromycin, Ciclosporin, Dronedaron) → Spiegel ↑; P-gp-Induktoren (Rifampicin, Johanniskraut) → Spiegel ↓."),
        ("Bei Substanzen mit {{c1::enger therapeutischer Breite}} und CYP-Abbau (z. B. Ciclosporin, Tacrolimus, Phenytoin, Carbamazepin, Theophyllin) ist bei Interaktionen ein {{c2::therapeutisches Drug-Monitoring (Spiegelkontrolle)}} nötig.",
         "Bei Neuansetzen oder Absetzen eines Hemmers/Induktors immer an die Komedikation denken."),
    ]),
    ("07 Pharmakogenetik", [
        ("Nach CYP-Genotyp unterscheidet man {{c1::Poor}}, {{c2::Intermediate}}, {{c3::Normal (Extensive)}} und {{c4::Ultrarapid}} Metabolizer.",
         "Ultrarapid Metabolizer haben meist zusätzliche Genkopien (Genduplikation), Poor Metabolizer zwei funktionslose Allele."),
        ("Bei {{c1::CYP2D6}} sind ca. {{c2::5–10 %}} der Europäer Poor Metabolizer.",
         "Ultrarapid Metabolizer: in Mitteleuropa ca. 1–10 %, in Nordafrika und auf der Arabischen Halbinsel deutlich häufiger."),
        ("{{c1::Codein}} wird über CYP2D6 durch O-Demethylierung zu {{c2::Morphin}} aktiviert.",
         "Poor Metabolizer: kaum analgetische Wirkung. Ultrarapid Metabolizer: Morphinintoxikation."),
        ("CYP2D6-Ultrarapid-Metabolizer unter Codein: Gefahr einer {{c1::Morphinintoxikation mit Atemdepression}}.",
         "Todesfälle bei Kindern nach Tonsillektomie und bei gestillten Säuglingen codeinbehandelter Mütter. Deshalb: Codein kontraindiziert bei Kindern < 12 Jahren, in der Stillzeit und bei bekannten Ultrarapid Metabolizern."),
        ("Auch {{c1::Tramadol}} wird über CYP2D6 zu seinem stärker µ-agonistischen Metaboliten {{c2::O-Desmethyltramadol}} aktiviert.",
         "Gleiche Problematik wie bei Codein (Wirkverlust bei PM, Atemdepression bei UM)."),
        ("{{c1::Tamoxifen}} wird über CYP2D6 zu {{c2::Endoxifen}} aktiviert; CYP2D6-Hemmer können seine Wirksamkeit mindern.",
         "Bei Depression unter Tamoxifen also kein Paroxetin/Fluoxetin."),
        ("CYP2C19-Poor-Metabolizer sind bei Ostasiaten mit ca. {{c1::15–20 %}} deutlich häufiger als bei Europäern (ca. 2–5 %).",
         "Folgen: Clopidogrel wirkt schlechter (Risiko von Stentthrombosen), PPI wirken stärker."),
        ("Bei CYP2C19-Poor-Metabolizern unter Clopidogrel ist die Plättchenhemmung {{c1::vermindert}}; als Alternative bieten sich {{c2::Prasugrel oder Ticagrelor}} an.",
         "Genotypisierung ist z. B. vor PCI möglich, aber nicht routinemäßig."),
        ("Varianten von {{c1::CYP2C9}} (z. B. *2, *3) und {{c2::VKORC1}} erklären einen Großteil der unterschiedlichen Warfarin-Dosisbedarfe.",
         "Träger brauchen niedrigere Dosen und haben ein höheres Blutungsrisiko bei Standarddosierung."),
        ("Kein CYP-Enzym: Langsame Acetylierer (Polymorphismus der {{c1::N-Acetyltransferase 2}}) haben unter Isoniazid ein höheres Risiko für {{c2::Polyneuropathie und Hepatotoxizität}}.",
         "Phase-II-Enzym. Auch medikamenteninduzierter Lupus durch Hydralazin und Procainamid tritt bei langsamen Acetylierern häufiger auf. Prophylaxe der INH-Polyneuropathie: Vitamin B6."),
        ("Kein CYP-Enzym: Vor Azathioprin/6-Mercaptopurin wird die Aktivität der {{c1::Thiopurin-Methyltransferase (TPMT)}} bestimmt, vor 5-FU/Capecitabin die der {{c2::Dihydropyrimidin-Dehydrogenase (DPD)}}.",
         "Mangel → schwere Myelosuppression bzw. lebensbedrohliche Toxizität. Weiteres Beispiel: UGT1A1-Varianten (Gilbert-Meulengracht) → Irinotecan-Toxizität."),
    ]),
    ("08 Paracetamol und Alkohol", [
        ("Paracetamol wird in therapeutischer Dosis überwiegend durch {{c1::Glucuronidierung}} und {{c2::Sulfatierung}} abgebaut.",
         "Nur ca. 5–10 % werden über CYP2E1 (und CYP3A4) zum reaktiven NAPQI oxidiert."),
        ("Der toxische Paracetamol-Metabolit heißt {{c1::NAPQI (N-Acetyl-p-benzochinonimin)}} und wird normalerweise durch {{c2::Glutathion}} entgiftet.",
         "Bei Überdosis werden Glucuronidierung und Sulfatierung gesättigt → mehr NAPQI → Glutathion erschöpft → kovalente Bindung an Proteine → zentrolobuläre Leberzellnekrose."),
        ("Antidot der Paracetamol-Vergiftung ist {{c1::N-Acetylcystein}}, das als {{c2::Glutathion-Vorstufe}} dient.",
         "Am wirksamsten innerhalb von 8–10 h nach Einnahme; Indikation über Serumspiegel (Nomogramm) bzw. Dosis."),
        ("Risikofaktoren für eine Paracetamol-Hepatotoxizität schon bei niedrigeren Dosen: {{c1::chronischer Alkoholkonsum}}, {{c2::Mangelernährung/Fasten}}, {{c3::Enzyminduktoren}}.",
         "Alkohol und Induktoren: mehr CYP2E1 → mehr NAPQI. Mangelernährung: weniger Glutathion."),
        ("Ethanol wird überwiegend über die {{c1::Alkoholdehydrogenase (ADH)}} abgebaut; bei hohen Konzentrationen und chronischem Konsum gewinnt das {{c2::MEOS (CYP2E1)}} an Bedeutung.",
         "MEOS ist induzierbar → Toleranzentwicklung bei Alkoholikern. Acetaldehyd wird von der Aldehyddehydrogenase (ALDH) weiter abgebaut (gehemmt durch Disulfiram, Metronidazol-Effekt umstritten)."),
    ]),
    ("09 Körpereigene CYP-Enzyme (Steroide, Vitamin D, Galle)", [
        ("Der erste Schritt der Steroidhormonsynthese, die Seitenkettenabspaltung von Cholesterin zu {{c1::Pregnenolon}}, wird von {{c2::CYP11A1 (Desmolase)}} in den Mitochondrien katalysiert.",
         "Geschwindigkeitsbestimmend ist der Cholesterintransport in die Mitochondrien durch das StAR-Protein (durch ACTH stimuliert)."),
        ("Die häufigste Ursache des adrenogenitalen Syndroms (> 90 %) ist ein Mangel an {{c1::21-Hydroxylase (CYP21A2)}}.",
         "Folge: Cortisol↓ und Aldosteron↓ (Salzverlust), Androgene↑ (Virilisierung). Neugeborenenscreening: 17-OH-Progesteron↑."),
        ("Beim Mangel an {{c1::11β-Hydroxylase (CYP11B1)}} entsteht trotz fehlendem Aldosteron eine {{c2::Hypertonie}}, weil sich {{c3::11-Desoxycorticosteron}} anhäuft.",
         "11-Desoxycorticosteron wirkt mineralokortikoid. Zusätzlich Virilisierung durch Androgenüberschuss."),
        ("Der Mangel an {{c1::17α-Hydroxylase (CYP17A1)}} führt zu Hypertonie und Hypokaliämie bei gleichzeitigem {{c2::Mangel an Sexualhormonen}}.",
         "Keine Androgen- und Östrogenbildung → ausbleibende Pubertät, bei 46,XY weibliches äußeres Genitale."),
        ("{{c1::Abirateron}} hemmt CYP17A1 und wird beim {{c2::metastasierten Prostatakarzinom}} eingesetzt.",
         "Wegen des Cortisolmangels und der ACTH-getriebenen Mineralokortikoid-Überproduktion (Hypertonie, Hypokaliämie) immer mit Prednison/Prednisolon kombiniert."),
        ("Die {{c1::Aromatase (CYP19A1)}} wandelt Androgene in Östrogene um; ihre Hemmer {{c2::Anastrozol, Letrozol, Exemestan}} werden beim HR-positiven Mammakarzinom der {{c3::postmenopausalen}} Frau eingesetzt.",
         "Postmenopausal entstehen Östrogene v. a. peripher (Fettgewebe) über Aromatase. Nebenwirkungen: Osteoporose, Arthralgien, Hitzewallungen."),
        ("Die Aldosteronsynthase ist {{c1::CYP11B2}} und wird v. a. durch {{c2::Angiotensin II und Kalium}} reguliert.",
         "Sie liegt in der Zona glomerulosa. CYP11B1 (Cortisol) liegt in der Zona fasciculata und wird durch ACTH reguliert."),
        ("{{c1::Metyrapon}} hemmt die 11β-Hydroxylase und wird (wie {{c2::Osilodrostat}} und Ketoconazol) zur Therapie des {{c3::Cushing-Syndroms}} eingesetzt.",
         "Ketoconazol hemmt in hoher Dosis mehrere Steroid-CYPs (Hepatotoxizität beachten)."),
        ("Die 25-Hydroxylierung von Vitamin D findet in der {{c1::Leber}} statt (v. a. {{c2::CYP2R1}}), die 1α-Hydroxylierung in der {{c3::Niere}} durch {{c4::CYP27B1}}.",
         "CYP27B1 wird durch PTH und Hypophosphatämie stimuliert und durch FGF23 und Calcitriol gehemmt. Abbau durch CYP24A1 (24-Hydroxylase)."),
        ("Bei {{c1::Sarkoidose}} bilden aktivierte Makrophagen in Granulomen unreguliert {{c2::1α-Hydroxylase}} → Calcitriol↑ → {{c3::Hyperkalzämie}}.",
         "Gleicher Mechanismus bei Tuberkulose und manchen Lymphomen. Therapie u. a. Glukokortikoide."),
        ("Das geschwindigkeitsbestimmende Enzym der Gallensäuresynthese ist die {{c1::Cholesterin-7α-Hydroxylase (CYP7A1)}}.",
         "Wird durch Gallensäuren über FXR gehemmt (negative Rückkopplung). Gallensäurebinder (Colestyramin) unterbrechen den enterohepatischen Kreislauf → CYP7A1↑ → LDL-Rezeptor↑ → LDL↓."),
        ("Auch {{c1::Thromboxan-A₂-Synthase}} und {{c2::Prostacyclin-Synthase}} gehören strukturell zur CYP450-Familie.",
         "CYP5A1 bzw. CYP8A1. Außerdem bilden CYP-Epoxygenasen aus Arachidonsäure EETs (Epoxyeicosatriensäuren, vasodilatierend)."),
    ]),
    ("10 Merkübersicht", [
        ("Merkliste starke CYP3A4-Hemmer: {{c1::Makrolide (Clarithro-, Erythromycin)}}, {{c2::Azole (Keto-, Itra-, Posa-, Voriconazol)}}, {{c3::Ritonavir/Cobicistat}}, {{c4::Grapefruitsaft}}.",
         "Mäßig: Verapamil, Diltiazem, Amiodaron, Fluconazol (hohe Dosis), Dronedaron.<br><br><table><tr><th>Hemmer</th><th>Hauptziel</th></tr><tr><td>Clarithromycin, Azole, Ritonavir</td><td>3A4</td></tr><tr><td>Fluconazol, Amiodaron, Metronidazol, Cotrimoxazol</td><td>2C9</td></tr><tr><td>Omeprazol, Fluvoxamin</td><td>2C19</td></tr><tr><td>Fluoxetin, Paroxetin, Bupropion</td><td>2D6</td></tr><tr><td>Ciprofloxacin, Fluvoxamin</td><td>1A2</td></tr></table>"),
        ("Merkliste starke CYP-Induktoren: {{c1::Rifampicin}}, {{c2::Carbamazepin}}, {{c3::Phenytoin}}, {{c4::Phenobarbital}}, {{c5::Johanniskraut}}.",
         "Dazu: Rauchen (1A2), chronischer Alkohol (2E1), Efavirenz, Rifabutin, Oxcarbazepin (schwächer), Apalutamid, Enzalutamid.<br><br>Faustregel: Induktion = Wirkverlust der Komedikation (langsam, Wochen); Hemmung = Toxizität der Komedikation (schnell, Tage)."),
        ("Interaktions-Faustregel: Ein CYP-{{c1::Hemmer}} erhöht die Spiegel normaler Substrate, {{c2::senkt}} aber die Wirkung von {{c3::Prodrugs}}, die über dieses Enzym aktiviert werden.",
         "Beispiele: Omeprazol + Clopidogrel, Paroxetin + Codein/Tamoxifen. Umgekehrt kann ein Induktor Prodrugs stärker aktivieren."),
    ]),
]
